# Generated by Django 5.2.5 on 2025-08-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('type', models.CharField(choices=[('COURSE', 'Curso'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminário'), ('RESEARCH', 'Pesquisa'), ('EXTENSION', 'Extensão'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('UPCOMING', 'Próximo'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado')], default='UPCOMING', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('time', models.CharField(blank=True, max_length=50, verbose_name='Horário')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('coordinator', models.CharField(max_length=100, verbose_name='Coordenador')),
                ('participants', models.IntegerField(default=0, verbose_name='Participantes')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=200, verbose_name='Requisito')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
        migrations.CreateModel(
            name='ActivityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('activities', models.ManyToManyField(blank=True, related_name='tags', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
    ]
