# Generated by Django 5.2.5 on 2025-10-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_task_taskattachment_taskcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskattachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='author',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
