# Generated by Django 5.2.5 on 2025-12-01 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_taskattachment_task_remove_taskcomment_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='coordinator',
            field=models.CharField(help_text='Ex: Prof. João Silva', max_length=200, verbose_name='Coordenador'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(help_text='Descrição detalhada da atividade (mínimo 10 caracteres)', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(help_text='Ex: Laboratório de Informática 1', max_length=200, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participants',
            field=models.PositiveIntegerField(default=1, help_text='Mínimo 1 participante', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Participantes'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada'), ('ACTIVE', 'Ativa'), ('UPCOMING', 'Próxima')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(help_text='Título da atividade (mínimo 3 caracteres)', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('COURSE', 'Curso'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminário'), ('RESEARCH', 'Pesquisa'), ('EXTENSION', 'Extensão'), ('OTHER', 'Outro')], default='COURSE', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
